### ISSUE TITLE
Winows: Cannot delete zip file because it is being used by some other process 

### ISSUE THREAD

**Issue by gamseb** [gamseb/starbound_mod_unpacker#2]

**Comment by Raizo575** [comment]
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'contents.pak' -> '1102394541-Customizable_Shuttlecraft.pak'

**Comment by gamseb** [comment]
I have modified the code so the script does not fail when a file cannot be deleted and it gets skipped instead
